# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "activerecord", "~> 7.0"

gem 'thin'

gem 'rack-cors'

gem 'rack-contrib'

gem 'sinatra'

gem 'sinatra-activerecord'

gem 'sqlite3'

gem 'rake'

gem 'require_all'

gem 'faker'

group :development do
    
    gem 'rerun'

    gem 'pry'
    
    end



gem "erb", "~> 3.0"

gem "shotgun", "~> 0.9.2"
